alias thq="ssh tictailhq.com"
alias ops="ssh ops.production.tictail.io"
alias msm="make serve-marketplace"
alias mss="HOSTNAME=bekkibraunberlin.tictail.com make serve-storefront"
alias mtest="./node_modules/mocha/bin/mocha $1 --watch --require test/domSetup"
